openai:
  api_key: "${OPENAI_API_KEY}"
  gpt4_endpoint: "https://api.openai.com/v1/engines/gpt-4/completions"
  codex_endpoint: "https://api.openai.com/v1/engines/code-davinci-002/completions"

huggingface:
  api_key: "YOUR_HUGGINGFACE_API_KEY"      # (Optional) API key for accessing models like CodeBERT, if required
  codebert_model: "microsoft/codebert-base"

llama_index:
  endpoint: "http://localhost:8000/api"    # Replace with your LlamaIndex endpoint or any relevant configuration
